apiVersion: v1
kind: Service
metadata:
  name: bigtablelite-service
  labels:
    app: bigtablelite
spec:
  selector:
    app: bigtablelite               
  ports:
    - name: grpc
      port: 50051                  # Cluster-facing port
      targetPort: 50051            # Container port
    - name: metrics
      port: 9090                   
      targetPort: 9090
