apiVersion: v1
kind: Service
metadata:
  name: bigtablelite-service
  labels:
    app: bigtablelite
spec:
  selector:
    app: bigtablelite               
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: metrics
      port: 9090
      targetPort: 9090
